title: ZZAlbert
description: |-
  I am a third year undergrad and a math TA at the University of Toronto.
  I write about mathematics and philosophy. This website contains
  information about me, my articles, and more.
author: Albert Hong

# url: "https://zzalbert.com"
# baseurl: ""

# markdown: kramdown
# theme: minima

permalink: pretty

collections:
  projects:
    output: true
    permalink: /notes/:slug/

  course-info:
    output: true
    permalink: /courses/:slug/

  blog-posts:
    output: true
    permalink: /blog/:slug/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projects-posts"
      nav-bar: "profile-nav"

  - scope:
      path: ""
      type: "course-info"
    values:
      layout: "courses-posts"
      nav-bar: "courses-nav"

  - scope:
      path: ""
      type: "blog-posts"
    values:
      layout: "blog-posts"
      nav-bar: "blog-nav"

# plugins:
#   - jekyll-feed
#   - jekyll-sitemap